# Generated by Django 4.2.1 on 2023-05-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_comment_comment_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_pic',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
